_wandb:
    value:
        cli_version: 0.23.1
        e:
            wv700ammmzvxwij3em100wlax7cj8uiy:
                args:
                    - --config
                    - plantvillage_latent.yml
                    - --doc
                    - plantvillage_cond
                    - --latent_cond
                    - --ni
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "17179869184"
                        used: "3701866496"
                email: thanhlamtba@gmail.com
                executable: /venv/main/bin/python
                git:
                    commit: 29bbd68d821e6d9ca7f81707a1eec0a4fd26e79c
                    remote: https://github.com/thanhlamauto/ddim.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-58ec0aa0-b916-0b74-d097-e869c90d9778
                host: 1cfeeb22d89d
                memory:
                    total: "202597416960"
                os: Linux-5.15.0-161-generic-x86_64-with-glibc2.39
                program: /workspace/ddim/main.py
                python: CPython 3.12.12
                root: /workspace/ddim
                startedAt: "2025-12-28T12:38:49.064728Z"
                writerId: wv700ammmzvxwij3em100wlax7cj8uiy
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 64
lr:
    value: 0.0001
n_iters:
    value: 200000
num_classes:
    value: 15
