_wandb:
    value:
        cli_version: 0.23.1
        e:
            p8ocmt3ame3c1x287jb023ek276exht3:
                args:
                    - --config
                    - plantvillage_latent.yml
                    - --exp
                    - exp
                    - --doc
                    - plantvillage_100steps
                    - --latent_cond
                    - --ni
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "9381213110272"
                        used: "4547818405888"
                email: thanhlamtba@gmail.com
                executable: /venv/main/bin/python3
                git:
                    commit: 9c21b3ed2d66e904b77b35519d9f88422fff56b5
                    remote: https://github.com/thanhlamauto/ddim.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-0ff9cab4-bfe1-9006-5855-7717504cf511
                host: 8caa12de97a3
                memory:
                    total: "811374333952"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /workspace/ddim/main.py
                python: CPython 3.12.12
                root: /workspace/ddim
                startedAt: "2025-12-30T14:08:48.982523Z"
                writerId: p8ocmt3ame3c1x287jb023ek276exht3
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 13
                - 15
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 64
lr:
    value: 0.0001
n_iters:
    value: 100000
num_classes:
    value: 15
